### PR TITLE
fixes login button issue #52

### PR DESCRIPTION
**Pull request by adityabisoyi**
fixes [Bug]: The login button turns white when hovered but the text does not turn black until you hover specifically on the text #52

### CODE REVIEW

**Comment by pythoniclaver** [comment]
> The inner text of the login button changes colour even if the cursor is not on th text but in the login button.

@adityabisoyi please link your pull request to the issue you're addressing. I won't merge until you correct your description

**Comment by pythoniclaver** [comment]
> > The inner text of the login button changes colour even if the cursor is not on th text but in the login button.
> 
> @adityabisoyi please link your pull request to the issue you're addressing. I won't merge until you correct your description

@adityabisoyi mention the issue you're addressing in your PR description, check other merged PRs to see how to do it.

**Comment by adityabisoyi** [comment]
@pythoniclaver I have edited the PR description. Is it correct ?

**Comment by pythoniclaver** [comment]
> @pythoniclaver I have edited the PR description. Is it correct ?

@adityabisoyi Yes it is correct. Thank you for your contribution. Don't forget to star and share our repository and also connect with me on GitHub and other platform. Thank you

**Pull request merged**
