### PR TITLE
Fixed the image that was getting cropped

### PR DESCRIPTION
**Pull request by souviksaha27**
I have fixed the image that was getting cropped, tell me if i need to make any more changes to it. Thank you.

### CODE REVIEW

**Comment by pythoniclaver** [comment]
Make a screenshot for proof man

**Comment by pythoniclaver** [comment]
> Make a screenshot for proof man

Or better still, wait for sometime for me to review it when I boot my system 👍

**Comment by pythoniclaver** [comment]
> I have fixed the image that was getting cropped, tell me if i need to make any more changes to it. Thank you.

Thank you for contributing to this repo, your PR have been reviewed and will be accepted. Happy Coding :)

**Comment by pythoniclaver** [comment]
@souviksaha27 this repo deserve a star from you don't we?
Give me a star man

**Comment by souviksaha27** [comment]
> @souviksaha27 this repo deserve a star from you don't we? Give me a star man

I gave you a star, thanks for helping me out 😃

**Pull request merged**
