### PR TITLE
I added navigation bar toggling on link clicked

### PR DESCRIPTION
**Pull request by olakayCoder1**
I notice on mobile view if the navigation bar is open and the and of the link is clicked is not closing, so I added a functionality to close it on link clicked. You can view it in scripts.js line 27 to 29

### CODE REVIEW

**Comment by pythoniclaver** [comment]
> I notice on mobile view if the navigation bar is open and the and of the link is clicked is not closing, so I added a functionality to close it on link clicked. You can view it in scripts.js line 27 to 29

@olakayCoder1  So I love what you did but there's no issue on this hence, I won't merge.

Create an issue first, then I will assign you to fix that issue, afterwards you can make I PR.

**Comment by pythoniclaver** [comment]
Create an issue man, I've got your back.

I will accept the issue if created!

**Comment by olakayCoder1** [comment]
Alrigth

**Comment by olakayCoder1** [comment]
Issue sent

**Pull request closed without merging**
